#//**********************************************************************
#//
#// Copyright (c) 2021 Microsoft Corporation. All rights reserved.
#//
#// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#// THE SOFTWARE.
#//
#
#//**********************************************************************​
#
#Author Kevin Bloom, Kevin.Bloom@Microsoft.com
#
#Get-DistributionListMembers_Recursive.ps1
#
#This script will pull the members of a DL and the members of the nested DL recursively
#This script can run against Exchange Server or Exchange Online
#How to run the script
# 1. Open Exchange Management Shell (EMS) or PowerShell and connect to Exchange Online
# 2. In either EMS or PowerShell, navigate to where the script is located and run it
# 3. The script will prompt you for the DL to target, please enter the DL name
# 4. Once complete, the script will save the exported CSV to the PS profile path named DistributionListMembers_Recursive.csv

$global:RootGroup
$global:Record = @()
$Global:ParentGroup = ""
$Global:TempParentGroup = ""
$Global:NestedGroup = ""
$Global:ColRecords = @()


Function Get-RootGroup{
        $GroupToExpand = Read-Host "Please enter the email address of the Distribution Group you would like to expand"
        Return $GroupToExpand
} 

Function Enumerate-GroupMember {
    Param ($Group)
    $Global:TempParentGroup = $Global:ParentGroup
    $Global:ParentGroup = $Group

    $GroupMembers = Get-DistributionGroupMember -Identity $Group -ResultSize unlimited

    Foreach ($Member in $GroupMembers){
        $global:Record = "" | Select-Object "PrimarySMTPAddress","Displayname","RecipientType","RootGroup","ParentGroup"
        $global:Record.PrimarySMTPAddress = $Member.PrimarySmtpAddress
        $global:Record.Displayname = $member.DisplayName
        $global:Record.RecipientType = $Member.RecipientType
        $global:Record.RootGroup = $global:RootGroup
        $global:Record.ParentGroup = $Global:ParentGroup
    
        $Global:ColRecords += $global:Record
    
        If ($Member.RecipientType -like "*group*"){
            $Global:ParentGroup = $TempParentGroup
            Enumerate-GroupMember $Member.PrimarySmtpAddress
        }
    }


}

$global:RootGroup = Get-RootGroup
Try {Get-DistributionGroup -Identity $RootGroup} Catch {Write-Host "Unable to get the Distribution Group, please re-enter DI's email address" ; Get-RootGroup}

$GroupMembers = Get-DistributionGroupMember -Identity $RootGroup -ResultSize unlimited

Foreach ($Member in $GroupMembers){
    $global:Record = "" | Select-Object "PrimarySMTPAddress","Displayname","RecipientType","RootGroup","ParentGroup"
    $global:Record.PrimarySMTPAddress = $Member.PrimarySmtpAddress
    $global:Record.Displayname = $member.DisplayName
    $global:Record.RecipientType = $Member.RecipientType
    $global:Record.RootGroup = $global:RootGroup
    $global:Record.ParentGroup = $global:RootGroup

    $Global:ColRecords += $global:Record

    If ($Member.RecipientType -like "*group*"){
        
        Enumerate-GroupMember $Member.PrimarySmtpAddress
    }
}

$Global:ColRecords | Export-Csv .\DistributionListMembers_Recursive.csv
# SIG # Begin signature block
# MIIn1QYJKoZIhvcNAQcCoIInxjCCJ8ICAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCCPaN5224G1fGVs
# wtS6pUGcbJtfQ8/1ewKnb35a4aTfb6CCDZowggYYMIIEAKADAgECAhMzAAACRKv5
# FGhmd6OiAAAAAAJEMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjEwODEyMTczODM1WhcNMjIwOTE1MTczODM1WjCBiDEL
# MAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
# bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWlj
# cm9zb2Z0IDNyZCBQYXJ0eSBBcHBsaWNhdGlvbiBDb21wb25lbnQwggEiMA0GCSqG
# SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCwzUai/r+FNF5K1JNkRMJxSz6JIvIfH9Ib
# NR8/3Q1/JIClI8sdX//mpKbiDRIn3BQ/q7lHoGYR6qjCXVxHbO1COlBo2YreHpVb
# Kf8AYkDmSOiA3jx7lJnKRxNDJDAM8j7MkanUHHlbChZFFVW6mnBW0HKVdM2W2p1c
# saCT8HjGvJKlfFBGj/cZbVC1n+fav/yrRK1sucxueSki0DTuiS/NLXbWQI2BnAo/
# iSUvQhOhVihZ0Q0PuCuwrQxUTxiS5g8Tp8v/rwkCBumlnuHfblLD6Gs3U78loWVN
# 9bZlh1W/qU2r86kHSBk3lIGCEk9QfHy4pQMvkNkIyGs6TVdsgmyrAgMBAAGjggGC
# MIIBfjAfBgNVHSUEGDAWBgorBgEEAYI3TBEBBggrBgEFBQcDAzAdBgNVHQ4EFgQU
# m8lV9bB/iidqnKSW6jWBahbwQ74wVAYDVR0RBE0wS6RJMEcxLTArBgNVBAsTJE1p
# Y3Jvc29mdCBJcmVsYW5kIE9wZXJhdGlvbnMgTGltaXRlZDEWMBQGA1UEBRMNMjMx
# NTIyKzQ2NjQxMzAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzcitW2oynUClTBUBgNV
# HR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2Ny
# bC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEGCCsGAQUFBwEBBFUw
# UzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9j
# ZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0MAwGA1UdEwEB/wQC
# MAAwDQYJKoZIhvcNAQELBQADggIBABDZCjHgdc3BNnV5L6eF7q2DieAoO76mgccC
# 1To5CRkkAxKZURF5KlPLZibjqmfnMZ2aVDzrSW5zxg8faWVlOOJ2Zh9moVhvIVSv
# vRDfL9E3eCkjVOk1LP3LSomITDZV/GdQ4cgNOueGGFRFoWG+RY5zLAkacpa1BxEx
# k/RA4qbBbwG9CbI+9E2g7ZTL/oK4Fm5TldW5zzXFQ9AoKpFp3miHRLwBKQEtptXf
# Ko1bJWB/uA0M87sWnKfpl8dgomi1ZhbnSS1cfG3eiz+4A91MRtQ4qqgqegsdrqMa
# 0xGxDefnMs2EutksEKQR9wtyuXZyG0HGAkmkuG36w0K1zxcdJLmMqHucnzQh5mCw
# od7JTVQtomeI6x/aWLTQ6d0PEhS3RkspTGJQW2nH6gI5R4U/Qr4vRqjPUK3dCf8r
# mpt2zTrvXZKYG5IOZ6LJJdCSIVQF8c6KkND6/X1MaAdan4oEZATgwrVFE9lhY1jv
# LAfi8YfRoebg5895jqg6924GCa7JzxkWiy9h5U5cIFLfoeLi6aLZ3m7EFyIxCpWU
# J4M9f2Rf7r9HLsBEe8VdStRTQPfnOBY5pR941DzxuwLs0w2yrPc3wVip0PXtl9qB
# z83IOl2ndypwNulkElMMhab9ju7Y+cRhGod8txO9AcNMjvL2Jxs3rtb6Z2LhO17U
# FqrtAEWnMIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkqhkiG9w0BAQsFADCB
# iDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
# ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMp
# TWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IDIwMTEwHhcNMTEw
# NzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQGEwJVUzETMBEGA1UE
# CBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
# b2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5n
# IFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAq/D6chAc
# Lq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03a8YS2AvwOMKZBrDI
# OdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akrrnoJr9eWWcpgGgXp
# ZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0RrrgOGSsbmQ1eKagYw8t
# 00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy4BI6t0le2O3tQ5GD
# 2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9sbKvkjh+0p2ALPVO
# VpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAhdCVfGCi2zCcoOCWY
# OUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8kA/DRelsv1SPjcF0P
# UUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTBw3J64HLnJN+/RpnF
# 78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmnEyimp31ngOaKYnhf
# si+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90lfdu+HggWCwTXWCV
# mj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0wggHpMBAGCSsGAQQB
# gjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2oynUClTAZBgkrBgEE
# AYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB
# /zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBaBgNVHR8EUzBRME+g
# TaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9N
# aWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsGAQUFBwEBBFIwUDBO
# BggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9N
# aWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNVHSAEgZcwgZQwgZEG
# CSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsGAQUFBwICMDQeMiAd
# AEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABlAG0AZQBuAHQALiAd
# MA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKbC5YR4WOSmUKWfdJ5
# DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11lhJB9i0ZQVdgMknzS
# Gksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6I/MTfaaQdION9Msm
# AkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0wI/zRive/DvQvTXv
# biWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560STkKxgrCxq2u5bLZ
# 2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQamASooPoI/E01mC8Cz
# TfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGaJ+HNpZfQ7l1jQeNb
# B5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ahXJbYANahRr1Z85el
# CUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA9Z74v2u3S5fi63V4
# GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33VtY5E90Z1WTk+/gFci
# oXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr/Xmfwb1tbWrJUnMT
# DXpQzTGCGZEwghmNAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
# aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
# cG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25pbmcgUENBIDIw
# MTECEzMAAAJEq/kUaGZ3o6IAAAAAAkQwDQYJYIZIAWUDBAIBBQCggbAwGQYJKoZI
# hvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcC
# ARUwLwYJKoZIhvcNAQkEMSIEIF3VVrwZH3ZQQSo1NtMyYw2VvdV2uY3sanyPthza
# y92kMEQGCisGAQQBgjcCAQwxNjA0oBSAEgBNAGkAYwByAG8AcwBvAGYAdKEcgBpo
# dHRwczovL3d3dy5taWNyb3NvZnQuY29tIDANBgkqhkiG9w0BAQEFAASCAQCTkMOK
# Q1ds1jyMAgdsLW7jyXALki12AldUfwlnA/8kihlD+p+R89vswHEXaJF1nYFOihdp
# sexgjjGHhg0luKqD3ZHgKzVNZFnZ5/Y1dzCIvvZCTcHteq2h3i0RFvbIcM5lcXRC
# Q84ro3fvce1eHQ+EZFpwMojKQGPgmL5aC1R3Q9gkvYUZlGPF/HGaLc2g9/K01Y00
# /t+mXc0NVVbEztj4fvHhFXdfLCc+vsyarP/bTJsGNWnJTe0GMb9P43PXxjtLR9LR
# iC1oExiuV3M8pYdE21EXOC3JNZyqeaWpnuPHttdI1xgBEvTRCWkOR2S4oVjoIFgb
# ZsVWnLSDz/u0Nn2/oYIXGTCCFxUGCisGAQQBgjcDAwExghcFMIIXAQYJKoZIhvcN
# AQcCoIIW8jCCFu4CAQMxDzANBglghkgBZQMEAgEFADCCAVkGCyqGSIb3DQEJEAEE
# oIIBSASCAUQwggFAAgEBBgorBgEEAYRZCgMBMDEwDQYJYIZIAWUDBAIBBQAEII1Y
# 1GSNlGrTo3y+NZGo9/HZyGuLXbc8trPwzo2fAB6uAgZhlV6jQ+sYEzIwMjExMjIw
# MjEzMDA5LjYzMlowBIACAfSggdikgdUwgdIxCzAJBgNVBAYTAlVTMRMwEQYDVQQI
# EwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3Nv
# ZnQgQ29ycG9yYXRpb24xLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJh
# dGlvbnMgTGltaXRlZDEmMCQGA1UECxMdVGhhbGVzIFRTUyBFU046M0JENC00Qjgw
# LTY5QzMxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2WgghFo
# MIIHFDCCBPygAwIBAgITMwAAAYm0v4YwhBxLjwABAAABiTANBgkqhkiG9w0BAQsF
# ADB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQD
# Ex1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDAeFw0yMTEwMjgxOTI3NDFa
# Fw0yMzAxMjYxOTI3NDFaMIHSMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
# Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
# cmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExp
# bWl0ZWQxJjAkBgNVBAsTHVRoYWxlcyBUU1MgRVNOOjNCRDQtNEI4MC02OUMzMSUw
# IwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNlMIICIjANBgkqhkiG
# 9w0BAQEFAAOCAg8AMIICCgKCAgEAvQZXxZFma6plmuOyvNpV8xONOwcYolZG/Bjy
# ZWGSk5JOGaLyrKId5VxVHWHlsmJE4SvnzsdpsKmVx8otONveIUFvSceEZp8VXmu5
# m1fu8L7c+3lwXcibjccqtEvtQslokQVx0r+L54abrNDarwFG73IaRidIS1i9c+un
# J8oYyhDRLrCysFAVxyQhPNZkWK7Z8/VGukaKLAWHXCh/+R53h42gFL+9/mAALxzC
# XXuofi8f/XKCm7xNwVc1hONCCz6oq94AufzVNkkIW4brUQgYpCcJm9U0XNmQvtro
# pYDn9UtY8YQ0NKenXPtdgLHdQ8Nnv3igErKLrWI0a5n5jjdKfwk+8mvakqdZmlOs
# eeOS1XspQNJAK1uZllAITcnQZOcO5ofjOQ33ujWckAXdz+/x3o7l4AU/TSOMzGZM
# whUdtVwC3dSbItpSVFgnjM2COEJ9zgCadvOirGDLN471jZI2jClkjsJTdgPk343T
# QA4JFvds/unZq0uLr+niZ3X44OBx2x+gVlln2c4UbZXNueA4yS1TJGbbJFIILAmT
# UA9Auj5eISGTbNiyWx79HnCOTar39QEKozm4LnTmDXy0/KI/H/nYZGKuTHfckP28
# wQS06rD+fDS5xLwcRMCW92DkHXmtbhGyRilBOL5LxZelQfxt54wl4WUC0AdAEolP
# ekODwO8CAwEAAaOCATYwggEyMB0GA1UdDgQWBBSXbx+zR1p4IIAeguA6rHKkrfl7
# UDAfBgNVHSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBfBgNVHR8EWDBWMFSg
# UqBQhk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NybC9NaWNyb3Nv
# ZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmwwbAYIKwYBBQUHAQEE
# YDBeMFwGCCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
# L2NlcnRzL01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNy
# dDAMBgNVHRMBAf8EAjAAMBMGA1UdJQQMMAoGCCsGAQUFBwMIMA0GCSqGSIb3DQEB
# CwUAA4ICAQCOtLdpWUI4KwfLLrfaKrLB92DqbAspGWM41TaO4Jl+sHxPo522uu3G
# KQCjmkRWreHtlfyy9kOk7LWax3k3ke8Gtfetfbh7qH0LeV2XOWg39BOnHf6mTcZq
# 7FYSZZch1JDQjc98+Odlow+oWih0Dbt4CV/e19ZcE+1n1zzWkskUEd0f5jPIUis3
# 3p+vkY8szduAtCcIcPFUhI8Hb5alPUAPMjGzwKb7NIKbnf8j8cP18As5IveckF0o
# h1cw63RY/vPK62LDYdpi7WnG2ObvngfWVKtwiwTI4jHj2cO9q37HDe/PPl216gSp
# UZh0ap24mKmMDfcKp1N4mEdsxz4oseOrPYeFsHHWJFJ6Aivvqn70KTeJpp5r+DxS
# qbeSy0mxIUOq/lAaUxgNSQVUX26t8r+fcikofKv23WHrtRV3t7rVTsB9YzrRaiik
# mz68K5HWdt9MqULxPQPo+ppZ0LRqkOae466+UKRY0JxWtdrMc5vHlHZfnqjawj/R
# sM2S6Q6fa9T9CnY1Nz7DYBG3yZJyCPFsrgU05s9ljqfsSptpFdUh9R4ce+L71SWD
# LM2x/1MFLLHAMbXsEp8KloEGtaDULnxtfS2tYhfuKGqRXoEfDPAMnIdTvQPh3GHQ
# 4SjkkBARHL0MY75alhGTKHWjC2aLVOo8obKIBk8hfnFDUf/EyVw4uTCCB3EwggVZ
# oAMCAQICEzMAAAAVxedrngKbSZkAAAAAABUwDQYJKoZIhvcNAQELBQAwgYgxCzAJ
# BgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25k
# MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jv
# c29mdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDEwMB4XDTIxMDkzMDE4
# MjIyNVoXDTMwMDkzMDE4MzIyNVowfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldh
# c2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBD
# b3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIw
# MTAwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDk4aZM57RyIQt5osvX
# JHm9DtWC0/3unAcH0qlsTnXIyjVX9gF/bErg4r25PhdgM/9cT8dm95VTcVrifkpa
# /rg2Z4VGIwy1jRPPdzLAEBjoYH1qUoNEt6aORmsHFPPFdvWGUNzBRMhxXFExN6AK
# OG6N7dcP2CZTfDlhAnrEqv1yaa8dq6z2Nr41JmTamDu6GnszrYBbfowQHJ1S/rbo
# YiXcag/PXfT+jlPP1uyFVk3v3byNpOORj7I5LFGc6XBpDco2LXCOMcg1KL3jtIck
# w+DJj361VI/c+gVVmG1oO5pGve2krnopN6zL64NF50ZuyjLVwIYwXE8s4mKyzbni
# jYjklqwBSru+cakXW2dg3viSkR4dPf0gz3N9QZpGdc3EXzTdEonW/aUgfX782Z5F
# 37ZyL9t9X4C626p+Nuw2TPYrbqgSUei/BQOj0XOmTTd0lBw0gg/wEPK3Rxjtp+iZ
# fD9M269ewvPV2HM9Q07BMzlMjgK8QmguEOqEUUbi0b1qGFphAXPKZ6Je1yh2AuIz
# GHLXpyDwwvoSCtdjbwzJNmSLW6CmgyFdXzB0kZSU2LlQ+QuJYfM2BjUYhEfb3BvR
# /bLUHMVr9lxSUV0S2yW6r1AFemzFER1y7435UsSFF5PAPBXbGjfHCBUYP3irRbb1
# Hode2o+eFnJpxq57t7c+auIurQIDAQABo4IB3TCCAdkwEgYJKwYBBAGCNxUBBAUC
# AwEAATAjBgkrBgEEAYI3FQIEFgQUKqdS/mTEmr6CkTxGNSnPEP8vBO4wHQYDVR0O
# BBYEFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMFwGA1UdIARVMFMwUQYMKwYBBAGCN0yD
# fQEBMEEwPwYIKwYBBQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lv
# cHMvRG9jcy9SZXBvc2l0b3J5Lmh0bTATBgNVHSUEDDAKBggrBgEFBQcDCDAZBgkr
# BgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUw
# AwEB/zAfBgNVHSMEGDAWgBTV9lbLj+iiXGJo0T2UkFvXzpoYxDBWBgNVHR8ETzBN
# MEugSaBHhkVodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0
# cy9NaWNSb29DZXJBdXRfMjAxMC0wNi0yMy5jcmwwWgYIKwYBBQUHAQEETjBMMEoG
# CCsGAQUFBzAChj5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRzL01p
# Y1Jvb0NlckF1dF8yMDEwLTA2LTIzLmNydDANBgkqhkiG9w0BAQsFAAOCAgEAnVV9
# /Cqt4SwfZwExJFvhnnJL/Klv6lwUtj5OR2R4sQaTlz0xM7U518JxNj/aZGx80HU5
# bbsPMeTCj/ts0aGUGCLu6WZnOlNN3Zi6th542DYunKmCVgADsAW+iehp4LoJ7nvf
# am++Kctu2D9IdQHZGN5tggz1bSNU5HhTdSRXud2f8449xvNo32X2pFaq95W2KFUn
# 0CS9QKC/GbYSEhFdPSfgQJY4rPf5KYnDvBewVIVCs/wMnosZiefwC2qBwoEZQhlS
# dYo2wh3DYXMuLGt7bj8sCXgU6ZGyqVvfSaN0DLzskYDSPeZKPmY7T7uG+jIa2Zb0
# j/aRAfbOxnT99kxybxCrdTDFNLB62FD+CljdQDzHVG2dY3RILLFORy3BFARxv2T5
# JL5zbcqOCb2zAVdJVGTZc9d/HltEAY5aGZFrDZ+kKNxnGSgkujhLmm77IVRrakUR
# R6nxt67I6IleT53S0Ex2tVdUCbFpAUR+fKFhbHP+CrvsQWY9af3LwUFJfn6Tvsv4
# O+S3Fb+0zj6lMVGEvL8CwYKiexcdFYmNcP7ntdAoGokLjzbaukz5m/8K6TT4JDVn
# K+ANuOaMmdbhIurwJ0I9JZTmdHRbatGePu1+oDEzfbzL6Xu/OHBE0ZDxyKs6ijoI
# Yn/ZcGNTTY3ugm2lBRDBcQZqELQdVTNYs6FwZvKhggLXMIICQAIBATCCAQChgdik
# gdUwgdIxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
# EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xLTArBgNV
# BAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJhdGlvbnMgTGltaXRlZDEmMCQGA1UE
# CxMdVGhhbGVzIFRTUyBFU046M0JENC00QjgwLTY5QzMxJTAjBgNVBAMTHE1pY3Jv
# c29mdCBUaW1lLVN0YW1wIFNlcnZpY2WiIwoBATAHBgUrDgMCGgMVACGlCa3ketye
# uey7bJNpWkMuiCcQoIGDMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldh
# c2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBD
# b3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIw
# MTAwDQYJKoZIhvcNAQEFBQACBQDla11XMCIYDzIwMjExMjIxMDM1MTUxWhgPMjAy
# MTEyMjIwMzUxNTFaMHcwPQYKKwYBBAGEWQoEATEvMC0wCgIFAOVrXVcCAQAwCgIB
# AAICBVcCAf8wBwIBAAICEVgwCgIFAOVsrtcCAQAwNgYKKwYBBAGEWQoEAjEoMCYw
# DAYKKwYBBAGEWQoDAqAKMAgCAQACAwehIKEKMAgCAQACAwGGoDANBgkqhkiG9w0B
# AQUFAAOBgQAuPkS6yO1ttLiuNr8rNbG/ScGrtZU875a1/vHtDI3OZiSaMY7fnwMl
# sgQ+TSJxgUYgFDZ8vdrnX3Vvplyh+9lLnEmBKtiqK8nSiVD3eswBL6nGGTC1gN/B
# rFyp6165a0D+GAg+4VIeJnMhjV7Iu1YB++QICPfDBdpJAkSgNVZk2TGCBA0wggQJ
# AgEBMIGTMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYD
# VQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAk
# BgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAABibS/hjCE
# HEuPAAEAAAGJMA0GCWCGSAFlAwQCAQUAoIIBSjAaBgkqhkiG9w0BCQMxDQYLKoZI
# hvcNAQkQAQQwLwYJKoZIhvcNAQkEMSIEIJqf1o5B43xcG4qxfr3zs//k5cJ/+k4h
# BPQBxL3nekD6MIH6BgsqhkiG9w0BCRACLzGB6jCB5zCB5DCBvQQgZndHMdxQV1Vs
# bpWHOTHqWEycvcRJm7cY69l/UmT8j0UwgZgwgYCkfjB8MQswCQYDVQQGEwJVUzET
# MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
# TWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1T
# dGFtcCBQQ0EgMjAxMAITMwAAAYm0v4YwhBxLjwABAAABiTAiBCBTZcU0BTbl6ZYz
# p0uDZo1s/JzSJ2kbTsCE29OosdjVfjANBgkqhkiG9w0BAQsFAASCAgAAy6lfFrUz
# 09Z35vZeY9ws/3uSKrcQDhXrZRVbprtOSlKDvwSZfB7WAtElIykwgYeid7OeZz3j
# Y41W/B0Cn9AduC15qCcl4+xm//7w/yWyabW0mdAqYyP/Lc35XOiEtxtW6f/norX4
# 1kCuWP/8Csi/HaWAc/etaThy4kloe8ccECr+JT1v8ULHoEzoAuxQmtTz5j/htlzB
# xLxZ65lmFFqTHx1jntZFQTqRBIGAuFbK5tejId7DVuTFmQW/MK+tytlAUP/Wh4rg
# loPgYdnfm2xfU5N8QiNSPCM2GnYLpGAteYvr9AL5gewOKsTn1Ee+A5zph2QGkfIJ
# h7XOJpwdSg8wIEWzOcLxQDiefrLEcOrGb3QOM6B8HRp+PiqhMBz2/2PluRvrF/D4
# I24zQxhPlxwHbsQCmKRZ0rKeOENFRSIo4ILBiggUYwuC4u4zaCE51ElRNsTdWuLX
# 54oTwG/3I3YV4/wryx6JiCYt6Fsa7dVOfK2cUTMj5Pq9t0zrxYYpkBLdIySBrgVm
# hYEnDCZE2P77clhHcHRYj8iEULLnM2MdcmXdj7Jv2XiQyVZL3KPib3recx0Kra7I
# 3v82n+nkUY2mgzNU6YrEp+Wvj1SP4MYc2/jJzFT5nGKTeYaLEqBEqac6I7xof4+s
# 1hej5FMddaOvxWSYvXrYjBltH8VyeGSq3Q==
# SIG # End signature block
